[tool.mypy]
warn_return_any = true
warn_unused_configs = true
exclude = [
    "deps",
    "src/gh/components",
    "src/gh/diffCheck/setup.py",
    "temp",
    "doc",
    "src/gh/diffCheck/diffCheck/__init__.py"
]

[[tool.mypy.overrides]]
module = [
    "Rhino.*",
    "rhinoscriptsyntax.*",
    "scriptcontext.*",
    "Grasshopper.*",
    "System.*",
    "GH_IO.*",
    "clr.*",
    "diffcheck_bindings",
    "diffCheck.diffcheck_bindings"
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pefile"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "diffCheck"
ignore_undefined_attributes = true



[tool.ruff]
exclude = [
    "doc/",
    "deps/",
    "temp/"
]

[tool.ruff.per-file-ignores]
"src/gh/diffCheck/diffCheck/__init__.py" = ["F401", "F403" ,"E402"]
