name: "pypi-build"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


env:
  BUILD_TYPE: Release
  VCPKG_FILE: c:/vcpkg/scripts/buildsystems/vcpkg.cmake

jobs:
  pypi_build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9.1

      - name: Create diff_check conda environment
        run: conda env create -f environment.yml
      
      - name: Activate diff_check conda environment
        run: conda activate diff_check

      - name: Cmake Configure
        run: |
          cmake -S . -B build -A x64 -DBUILD_PYTHON_MODULE=ON -DBUILD_TESTS=OFF -DRUN_TESTS=OFF
      - name: CMake Build
        run: cmake --build build --config Release

      - name: Copying the dlls/pyd for python pypi package
        run: |
          copy ${{github.workspace}}/build/bin/Release/diffCheck.dll ${{github.workspace}}/src/gh/diffCheck/diffCheck/dlls
          copy ${{github.workspace}}/build/bin/Release/Open3D.dll ${{github.workspace}}/src/gh/diffCheck/diffCheck/dlls
          copy ${{github.workspace}}/build/Release/*.pyd ${{github.workspace}}/src/gh/diffCheck/diffCheck

      - name: Build wheel
        run: |
          cd ${{github.workspace}}/src/gh/diffCheck/
          python setup.py bdist_wheel
          cd ${{github.workspace}}

      ## for debug only
      # - name: Upload wheel
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: wheel
      #     path: ${{github.workspace}}/src/gh/diffCheck/dist/
