name: "win-build"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]



env:
  BUILD_TYPE: Release
  VCPKG_FILE: c:/vcpkg/scripts/buildsystems/vcpkg.cmake

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: CMAKE Configure
        run: ${{github.workspace}}/cmake/config.bat
      - name: CMake Build
        run: ${{github.workspace}}/cmake/build.bat