name: yak-build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-ghusers:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: NuGet/setup-nuget@v1.0.5

      - name: Install CPython and pythonnet package
        run: |
          choco install python --version=3.9.10
          python -m pip install pythonnet==3.0.3
          python -m pip install invoke

      - name: create the build folder
        run: mkdir build

      - name: Flag the ghuser codes with the correct package version
        run: invoke flagerize

      - name: Invoke the componentizer
        run: |
          mkdir build/gh
          invoke ghcomponentize

      - uses: actions/upload-artifact@v4
        with:
          name: ghuser-components
          path: build/gh

  build-yak-package:
    runs-on: windows-latest
    needs: build-ghusers

    steps:
      - uses: actions/checkout@v2

      - name: Install Python and pythonnet
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.10'

      - name: Install Python dependencies
        run: |
            python -m pip install --upgrade pip
            pip install invoke
            pip install pythonnet

      - name: Download the ghuser components
        uses: actions/download-artifact@v4
        with:
          name: ghuser-components
          path: build/gh

      - name: Build the yak package
        run: invoke yakerize

    ## for debug only
    #   - name: Save artifact the yak package as an artifact
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: yak_package_artifact
    #       path: build/yak/*.yak


